os:
  - linux
  - osx

language: node_js

node_js:
  - '7'

branches:
  only:
    - master

before_script:
  - chmod +x ./test/travis-build.sh

script: ./test/travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
