os:
  - osx
language: node_js
node_js:
  - "node"
install:
- yarn install
before_script: 
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
- yarn dev
script:
- yarn test
cache:
  directories:
    - node_modules

