os:
  - osx
addons:
  apt:
    packages:
    - xvfb
language: node_js
node_js:
  - "node"
install:
  - yarn install
  - cd ./app
  - yarn install 
  - cd ../
before_script:
  - chmod +x ./test/travis-build.sh
  - ./test/travis-build.sh
  - yarn build
script:
  - yarn test
cache:
  directories:
    - node_modules

